[package]
name = "axum-static-file-server"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
axum = { version = "0.2.2" }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
tower-http = { version = "0.1", features = ["fs", "trace"] }
